// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartServices() {
  return window['go']['main']['App']['StartServices']();
}

export function StopServices() {
  return window['go']['main']['App']['StopServices']();
}
